export const SET_MENU_REQUEST = 'SET_MENU_REQUEST';
export const SET_MENU_REQUEST_SUCCESS = 'SET_MENU_REQUEST_SUCCESS';

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';

export const CHANGE_SELECTED_OPTION = 'CHANGE_SELECTED_OPTION';
export const CLEAR_SELECTED_OPTION = 'CLEAR_SELECTED_OPTION';

export const CHANGE_INGREDIENT_STATUS = 'CHANGE_INGREDIENT_STATUS';

export const ADD_TO_ORDERS = 'ADD_TO_ORDERS';
export const SHOW_ORDERED_DISHES = 'SHOW_ORDERED_DISHES';

export const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';

export const SET_DEFAULT_AMOUNT_OF_CALORIES = 'SET_DEFAULT_AMOUNT_OF_CALORIES';
export const COUNT_OF_THE_CALORIE = 'COUNT_OF_THE_CALORIE';
